name = "GaussianBasis"
uuid = "9bb1a3dc-0d1c-467e-84f5-0c4ef701360a"
authors = ["gustavojra <gustavo.aroeira@gmail.com>"]
version = "0.4.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Molecules = "5de6a177-b489-40a9-b2f4-524242b9b679"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
libcint_jll = "574b78ca-bebd-517c-801d-4735c93a9686"

[compat]
Combinatorics = "1"
Formatting = "^0.4"
HDF5 = "^0.15.6"
SpecialFunctions = "2"
StaticArrays = "1.4"
Molecules = "0.3"
julia = "^1.6"
libcint_jll = "5"
